name: ui_elements
description: A new Flutter project.
publish_to: "none"
version: 1.0.2+4

environment:
    sdk: ">=2.19.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    animations: ^2.0.7
    percent_indicator: ^4.2.3
    http: ^1.1.0
    intl: ^0.18.0
    url_launcher: ^6.1.10
    path: ^1.8.3
    path_provider: ^2.0.14
    isar: ^3.1.0
    isar_flutter_libs: ^3.1.0
    share_plus: ^7.0.1
    font_awesome_flutter: ^10.4.0
    shared_preferences: ^2.1.1
    provider: ^6.0.5
    vibration: ^1.7.7
    file_picker: ^5.3.0
    csv: ^5.0.2
    graphql: ^5.1.2
    flutter_svg: ^2.0.7
    fl_chart: ^0.63.0
    cached_network_image: ^3.2.3
    flutter_heatmap_calendar:
      git:
        url: https://github.com/eterniter06/flutter_heatmap_calendar
    flutter_animate: ^4.2.0+1
    uni_links: ^0.5.1
    reorderable_grid_view: ^2.2.8
    package_info_plus: ^8.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    mocktail: ^1.0.1
    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    isar_generator: ^3.1.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/languages/

    fonts:
        - family: FiraCode
          fonts:
              - asset: fonts/FiraCode-Regular.ttf
        - family: Overpass
          fonts:
              - asset: fonts/Overpass-Regular.ttf
