name: ui_elements
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=2.19.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    animations: ^2.0.7
    percent_indicator: ^4.2.3
    http: ^0.13.5
    intl: ^0.18.0
    url_launcher: ^6.1.10
    shared_preferences: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/

    fonts:
        - family: FiraCode
          fonts:
              - asset: fonts/FiraCode-Regular.ttf
        - family: Overpass
          fonts:
              - asset: fonts/Overpass-Regular.ttf
